[book]
authors = ["Steve Marschner", "Peter Shirley"]
language = "cn"
multilingual = false
src = "src"
title = "计算机图形学基础"
description = """Drawing on an impressive roster of experts in the field, Fundamentals of Computer Graphics, Fifth Edition offers an ideal resource for computer course curricula as well as a user-friendly personal or professional reference"""